export const OIDC_ACCOUNT_SERVICE = 'NESTJS:OIDC_ACCOUNT_SERVICE';
export const OIDC_CONFIGURATION = 'NESTJS:OIDC_CONFIGURATION';
export const OIDC_ADAPTER_REDIS_HOST = 'NESTJS:OIDC_ADAPTER_REDIS_HOST';
